docs: Update README
extism/zig-pdk pull request #17
Opened 2023-11-21 15:17 UTC by mhmd-azeez

The idea for this is to be similar to rust-pdk https://github.com/extism/rust-pdk

Fixes #16

2023-11-21 15:20 UTC, mhmd-azeez commented
Not sure why there were some build errors on my machine

2023-11-21 21:38 UTC, nilslice commented
@mhmd-azeez - thank you! which version of Zig are you using with this? 

I'm on `0.12.0-dev.978+78855bd21`, and seem to need to use `std.builtin.Endian.Little` (vs. `std.builtin.Endian.little`, note the capitalization of `little`). I am not sure if this is a version thing or a typo haha

2023-11-22 05:20 UTC, mhmd-azeez commented
@nilslice seems like they have changed it to `little` [in the newer versions](https://github.com/ziglang/zig/blob/master/lib/std/builtin.zig#L454):
```
PS D:\dylibso\zig-pdk> zig build
zig build-exe Basic example Debug wasm32-freestanding-musl: error: the following command failed with 2 compilation errors:
D:\tools\zig.exe build-exe D:\dylibso\zig-pdk\examples\basic.zig --cache-dir D:\dylibso\zig-pdk\zig-cache --global-cache-dir C:\Users\muham\AppData\Local\zig --name Basic example -rdynamic -target wasm32-freestanding-musl -mcpu generic --mod extism-pdk::D:\dylibso\zig-pdk\src\main.zig --deps extism-pdk --listen=-
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install Basic example transitive failure
   └─ zig build-exe Basic example Debug wasm32-freestanding-musl 2 errors
src\main.zig:31:73: error: enum 'builtin.Endian' has no member named 'Little'
            std.mem.writeInt(u64, buf[i..][0..8], x, std.builtin.Endian.Little);
                                                                        ^~~~~~
D:\tools\lib\std\builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
referenced by:
    count_vowels: examples\basic.zig:19:25
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src\Memory.zig:42:78: error: enum 'builtin.Endian' has no member named 'Little'
        const data = std.mem.readInt(u64, buf[i..][0..8], std.builtin.Endian.Little);
                                                                             ^~~~~~
D:\tools\lib\std\builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
PS D:\dylibso\zig-pdk> zig version
0.12.0-dev.1664+8ca4a5240
```

2023-11-22 05:20 UTC, mhmd-azeez commented
Hah! it's been changed 3 weeks ago: https://github.com/ziglang/zig/commit/3fc6fc68129219a026ae3d7dff82513758e33a21

2023-11-22 05:25 UTC, nilslice commented
haha! thank you for looking at that. sorry I was behind a few versions... I think our strategy has been to follow the latest versions as close as possible. 

@usdogu can advise, as the expert Zig extism contributor!

2023-11-22 12:21 UTC, mhmd-azeez commented
In addition to reviewing the API changes, please also take a close look at the examples to make sure allocations and deallocations are properly managed

2023-11-22 16:45 UTC, bhelx commented
Thanks for taking this one on!

2023-11-22 19:55 UTC, usdogu requested changes
Other than these, LGTM!

2023-11-22 19:55 UTC, usdogu commented on src/main.zig
> +            return std.mem.readPackedInt(i32, buf, 0, .little);
```suggestion
            return std.mem.readPackedInt(T, buf, 0, .little);
```

2023-11-22 19:55 UTC, usdogu commented on src/main.zig
>          extism.extism_var_set(mem.offset, 0);
```suggestion
        extism.var_set(mem.offset, 0);
```

2023-11-22 19:55 UTC, usdogu commented on src/main.zig
> +        const buffer = try self.allocator.alloc(u8, 8);
```suggestion
        const buffer = try self.allocator.alloc(u8, @sizeOf(T));
```

2023-11-22 19:55 UTC, usdogu commented on src/main.zig
> +        errdefer self.allocator.free(buffer);
```suggestion
        defer self.allocator.free(buffer);
```

2023-11-23 10:29 UTC, mhmd-azeez commented on src/main.zig
> +            return std.mem.readPackedInt(i32, buf, 0, .little);
Great catch!

2023-11-23 10:32 UTC, mhmd-azeez commented
@usdogu thank you very much for you suggestions!

2023-11-23 10:45 UTC, mhmd-azeez commented
Also added the readme examples to `basic.zig`, we can turn them into integration tests in a separate PR

2023-11-23 12:50 UTC, usdogu approved these changes

2023-11-24 17:57 UTC, nilslice commented
Going to merge this one & make sure #19 works based on it

2023-11-24 17:57 UTC, merged